import React,{useState} from 'react';
import {login,register,logout,resetPassword} from './firebaseService';
import {firebaseConfigured} from './firebase';
export default function AuthPanel({user,onClose,onUser,adminMode}){
 const[mode,setMode]=useState('login'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function forgot(){if(!email){setError('Enter your email first.');return}try{await resetPassword(email);setNotice('Password reset email sent.')}catch(e){setError(e.message)}}
 async function submit(e){e.preventDefault();setError('');setNotice('');setBusy(true);try{const u=mode==='login'?await login(email,password):await register({name,email,phone,password});onUser(u);onClose()}catch(err){setError(err.code==='auth/invalid-credential'?'Email or password is incorrect.':err.message)}finally{setBusy(false)}}
 if(user)return <div className="account-card"><h2>You’re signed in.</h2><p>{user.email}</p><button className="primary full" onClick={async()=>{await logout();onUser(null);onClose()}}>Sign out</button></div>;
 return <div className="auth-card"><button className="close" onClick={onClose}>×</button><small>{adminMode?'ADMIN ACCESS':mode==='login'?'WELCOME BACK':'JOIN WEARVIBE'}</small><h2>{adminMode?<span>Sign in to<br/><i>Admin Dashboard</i></span>:mode==='login'?<span>Sign in to your<br/><i>account</i></span>:<span>Create your<br/><i>account</i></span>}</h2>{!firebaseConfigured&&<p className="notice">Add your Firebase values to `.env` to enable account creation.</p>}<form onSubmit={submit}>{mode==='register'&&!adminMode&&<><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Ayesha Babar"/></label><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value)} required placeholder="03001234567"/></label></>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="6" placeholder="At least 6 characters"/></label>{error&&<p className="error">{error}</p>}<button className="primary full" disabled={busy||!firebaseConfigured}>{busy?'Please wait…':adminMode?'Admin Sign in ↗':mode==='login'?'Sign in ↗':'Create account ↗'}</button></form>{!adminMode&&<button type="button" className="switch" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'New to WearVibe? Create an account':'Already have an account? Sign in'}</button>}{mode==='login'&&<button type="button" className="switch" onClick={forgot}>Forgot password?</button>}{notice&&<p className="notice">{notice}</p>}</div>
}